# Generated by Django 5.2.6 on 2025-09-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twin_app', '0004_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
    ]
